version: '3'
services:
  # myapplication:
  #   image: mongodb/mongodb-community-server:6.0-ubi8
  #   environment:
  #     - CONN_STR=mongodb://user:pass@mongodb
  #   command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
  #   depends_on:
  #     - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=farshana
      - MONGODB_INITDB_ROOT_PASSWORD=farshana
    volumes:
        - mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - foodNetwork

volumes:
  mongo-data:

networks:
  foodNetwork:
    external: true